const ACTIONS = {
  
  DELETE_PLAN: "DELETE_PLAN",
  EDIT_PLAN: "EDIT_PLAN",
  SHOWLOADER: "SHOWLOADER",
  HIDELOADER: "HIDELOADER",
  ADD_PLAN: "ADD_PLAN",
  ADD_ITEM: "ADD_ITEM",
  SAVE_ITEM: "SAVE_ITEM",
  DELETE_ITEM: "DELETE_ITEM",
  FETCH_ALL_PLANS_AND_ITEMS_USERS: "FETCH_ALL_PLANS_AND_ITEMS_USERS",
  ADD_USER:"ADD_USER", 
  DELETE_USER:"DELETE_USER",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
};

export default ACTIONS;
