const ACTIONS = {
  FETCH_ALL_PLANS: "FETCH_ALL_PLANS",
  DELETE_PLAN: "DELETE_PLAN",
  EDIT_PLAN: "EDIT_PLAN",
  SHOWLOADER: "SHOWLOADER",
  HIDELOADER: "HIDELOADER",
  ADD_PLAN: "ADD_PLAN",
  ADD_ITEM: "ADD_ITEM",
};

export default ACTIONS;
